#!/bin/sh

if [ "$#" -eq 0 ]; then
    DATE=$(date +"%Y-%m-%d_%H%M%S")
    FILE="$HOME/Pictures/screenshots/$DATE.png"
    RES=$(xrandr --current | grep '*' | awk '{print $1}')
    ffmpeg -f x11grab -video_size $RES -i :0.0+0,0 -vframes 1 $FILE
    echo "Screenshot saved to $FILE"
    exit 1
fi

# Iterate over command-line arguments
while [[ $# -gt 0 ]]; do
    key="$1"

    # Check for different flag arguments
    case $key in
        -h|--help)
            # Code to handle the "-h" or "--help" flag
            echo "Displaying help..."
            exit 0
            ;;
        -s)
            # Selection
            DATE=$(date +"%Y-%m-%d_%H%M%S")
            FILE="/$HOME/Pictures/screenshots/$DATE.png"
            ffmpeg -f x11grab -video_size $(hacksaw -f '%wx%h -i :0.0+%x,%y') -vframes 1 $FILE
            echo "Screenshot saved to $FILE"
            exit 1
            ;;
        -c)
            # Full screen to clipboard
            DATE=$(date +"%Y-%m-%d_%H%M%S")
            FILE="/tmp/$DATE.png"
            RES=$(xrandr --current | grep '*' | awk '{print $1}')
            ffmpeg -f x11grab -video_size $RES -i :0.0+0,0 -vframes 1 $FILE
            xclip -selection clipboard -t image/png -i $FILE
            rm $FILE
            echo "Screenshot saved to clipboard"
            exit 1
            ;;
        -sc)
            # Selection to clipboard
            DATE=$(date +"%Y-%m-%d_%H%M%S")
            FILE="/tmp/$DATE.png"
            ffmpeg -f x11grab -video_size $(hacksaw -f '%wx%h -i :0.0+%x,%y') -vframes 1 $FILE
            xclip -selection clipboard -t image/png -i $FILE
            rm $FILE
            echo "Screenshot saved to clipboard"
            exit 1
            ;;
        *)
            # Code to handle unrecognized arguments
            echo "Unrecognized argument: $key"
            exit 1
            ;;
    esac
done